#!/usr/bin/env ruby

require "optparse"

require "./lib/calendar"
require "./lib/event_data"

optparse = OptionParser.new do |opts|
  opts.banner = "Usage: ./run [options] data-file.yml"

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end

optparse.parse!

filename = ARGV[0]

if filename.nil?
  $stderr.puts optparse
  exit 64
end

data = EventData.from_yaml(filename)
calendar = Calendar.new

data.events.each do |event|
  calendar.create_events(event[:name], event[:date].month, event[:date].day)
end

puts calendar.to_ical
