#!/usr/bin/env ruby

require "optparse"

require "./lib/calendar"
require "./lib/event_data"

options = {
  years: Calendar::DEFAULT_YEARS_TO_ADD
}

optparse = OptionParser.new do |opts|
  opts.banner = "Usage: ./run [options] data-file.yml"

  opts.on("-yYEARS", "--years=YEARS", Integer, "Number of years for which to create events (Defaults to #{Calendar::DEFAULT_YEARS_TO_ADD})") do |years|
    options[:years] = years
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end

optparse.parse!

filename = ARGV[0]

if filename.nil?
  $stderr.puts optparse
  exit 64
end

data = EventData.from_yaml(filename)
calendar = Calendar.new(options[:years])

data.events.each do |event|
  calendar.create_events(event[:name], event[:date].month, event[:date].day)
end

puts calendar.to_ical
